"""add preview environment event types

Revision ID: 6682e94a52ab
Revises: e9e5c0fd98fa
Create Date: 2026-03-01 10:14:59.814673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6682e94a52ab'
down_revision: Union[str, Sequence[str], None] = 'e9e5c0fd98fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('environments', 'cpu_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('environments', 'memory_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('environments', 'cpu_limit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('environments', 'memory_limit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('environments', 'memory_limit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('environments', 'cpu_limit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('environments', 'memory_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('environments', 'cpu_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
