"""initial schema: PR, Pipeline, Stage, Environment, Event

Revision ID: e9e5c0fd98fa
Revises: 
Create Date: 2026-02-14 20:40:21.527700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e5c0fd98fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MERGED', 'CLOSED', name='prstatus'), nullable=False),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('latest_commit_sha', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_github_pr_number'), 'pull_requests', ['github_pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_status'), 'pull_requests', ['status'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pull_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('namespace', sa.String(length=63), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONING', 'RUNNING', 'DEGRADED', 'DESTROYING', 'DESTROYED', 'FAILED', name='environmentstatus'), nullable=False),
    sa.Column('argocd_app_name', sa.String(length=255), nullable=False),
    sa.Column('cpu_request', sa.String(length=20), nullable=False),
    sa.Column('memory_request', sa.String(length=20), nullable=False),
    sa.Column('cpu_limit', sa.String(length=20), nullable=False),
    sa.Column('memory_limit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace')
    )
    op.create_index(op.f('ix_environments_pull_request_id'), 'environments', ['pull_request_id'], unique=True)
    op.create_index(op.f('ix_environments_status'), 'environments', ['status'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pull_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='pipelinestatus'), nullable=False),
    sa.Column('github_run_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_pull_request_id'), 'pipelines', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pipelines_status'), 'pipelines', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Enum('PR_OPENED', 'PR_UPDATED', 'PR_CLOSED', 'PR_MERGED', 'PIPELINE_STARTED', 'STAGE_STARTED', 'STAGE_COMPLETED', 'STAGE_FAILED', 'ENV_PROVISIONING', 'ENV_READY', 'ENV_DESTROYING', 'ENV_DESTROYED', 'ENV_FAILED', name='eventtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pull_request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('pipeline_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_pipeline_id'), 'events', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_events_pull_request_id'), 'events', ['pull_request_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pipeline_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stage_type', sa.Enum('LINT', 'TEST', 'SONARQUBE', 'BUILD_IMAGE', 'DEPLOY', name='stagetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_events_pull_request_id'), table_name='events')
    op.drop_index(op.f('ix_events_pipeline_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_pipelines_status'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_pull_request_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_environments_status'), table_name='environments')
    op.drop_index(op.f('ix_environments_pull_request_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_pull_requests_status'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_pr_number'), table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
